package edu.pitt.cs;

// Generated by Selenium IDE
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1LINKS() {
    driver.get("http://localhost:8080/");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'/reset\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST2RESET() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
    driver.findElement(By.xpath("//a[contains(@href, \'/reset\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 1. Jennyanydots\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 2. Old Deuteronomy\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 3. Mistoffelees\')]"));
      assert(elements.size() > 0);
    }
    vars.put("catOne", driver.findElement(By.xpath("//div[@id=\'listing\']/ul/li")).getText());
    assertEquals(vars.get("catOne").toString(), "ID 1. Jennyanydots");
    vars.put("catTwo", driver.findElement(By.xpath("//div/ul/li[2]")).getText());
    assertEquals(vars.get("catTwo").toString(), "ID 2. Old Deuteronomy");
    vars.put("catThree", driver.findElement(By.xpath("//div/ul/li[3]")).getText());
    assertEquals(vars.get("catThree").toString(), "ID 3. Mistoffelees");
  }
  @Test
  public void tEST3CATALOG() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Catalog")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(3) > img"));
      assert(elements.size() > 0);
    }
    {
      WebElement element = driver.findElement(By.xpath("//img[@alt=\'Old Deuteronomy\']"));
      String attribute = element.getAttribute("src");
      vars.put("image2", attribute);
    }
    assertEquals("http://localhost:8080/images/cat2.jpg",vars.get("image2").toString());
  }
  @Test
  public void tEST4LISTING() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Catalog")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'listing\']/ul/li[3]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'listing\']/ul/li[4]"));
      assert(elements.size() == 0);
    }
    vars.put("thirdElement", driver.findElement(By.xpath("//div[@id=\'listing\']/ul/li[3]")).getText());
    assertEquals(vars.get("thirdElement").toString(), "ID 3. Mistoffelees");
  }
  @Test
  public void tEST5RENTACAT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[@onclick=\'rentSubmit()\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[@onclick=\'returnSubmit()\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST6RENT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("rentID")).click();
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
    vars.put("rented", driver.findElement(By.xpath("//li[contains(.,\'Rented out\')]")).getText());
    assertEquals(vars.get("rented").toString(), "Rented out");
    vars.put("catTwo", driver.findElement(By.xpath("//li[contains(.,\'ID 2. Old Deuteronomy\')]")).getText());
    assertEquals(vars.get("catTwo").toString(), "ID 2. Old Deuteronomy");
    vars.put("catThree", driver.findElement(By.xpath("//li[contains(.,\'ID 3. Mistoffelees\')]")).getText());
    assertEquals(vars.get("catThree").toString(), "ID 3. Mistoffelees");
    vars.put("rentGood", driver.findElement(By.xpath("//div[@id=\'rentResult\']")).getText());
    assertEquals(vars.get("rentGood").toString(), "Success!");
  }
  @Test
  public void tEST7RETURN() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("returnID")).click();
    driver.findElement(By.id("returnID")).sendKeys("2");
    driver.findElement(By.cssSelector(".form-group:nth-child(4) .btn")).click();
    vars.put("catOne", driver.findElement(By.xpath("//div[@id=\'listing\']/ul/li")).getText());
    assertEquals(vars.get("catOne").toString(), "ID 1. Jennyanydots");
    vars.put("catTwo", driver.findElement(By.xpath("//div[@id=\'listing\']/ul/li[2]")).getText());
    assertEquals(vars.get("catTwo").toString(), "ID 2. Old Deuteronomy");
    vars.put("catThree", driver.findElement(By.xpath("//div[@id=\'listing\']/ul/li[3]")).getText());
    assertEquals(vars.get("catThree").toString(), "ID 3. Mistoffelees");
    vars.put("returnGood", driver.findElement(By.xpath("//div[@id=\'returnResult\']")).getText());
    assertEquals(vars.get("returnGood").toString(), "Success!");
  }
  @Test
  public void tEST8FEEDACAT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[@onclick=\'feedSubmit()\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST9FEED() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    driver.findElement(By.id("catnips")).click();
    driver.findElement(By.id("catnips")).sendKeys("6");
    driver.findElement(By.xpath("//button[@onclick=\'feedSubmit()\']")).click();
    vars.put("feedGood", driver.findElement(By.xpath("//div[@id=\'feedResult\']")).getText());
    assertEquals(vars.get("feedGood").toString(), "Nom, nom, nom.");
  }
  @Test
  public void tEST10GREETACAT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Greet-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//h4[contains(.,\'Meow!Meow!Meow!\')]"));
      assert(elements.size() > 0);
    }
    vars.put("greetingGood", driver.findElement(By.xpath("//h4[contains(.,\'Meow!Meow!Meow!\')]")).getText());
    assertEquals(vars.get("greetingGood").toString(), "Meow!Meow!Meow!");
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//h4[contains(.,\'Meow! from Jennyanydots.\')]"));
      assert(elements.size() > 0);
    }
    vars.put("catoneGreeting", driver.findElement(By.xpath("//div[@id=\'greeting\']/h4")).getText());
    assertEquals(vars.get("catoneGreeting").toString(), "Meow! from Jennyanydots.");
  }
  /* 
  @Test
  public void dEFECT1FUNFEEDACAT1() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    driver.findElement(By.id("catnips")).click();
    driver.findElement(By.id("catnips")).sendKeys("-3");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.id("feedResult")).getText(), is("\\\"Cat fight!\\\""));
  }
  @Test
  public void dEFECT2FUNGREETACAT() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    driver.findElement(By.linkText("Greet-A-Cat")).click();
    assertThat(driver.findElement(By.xpath("//div[2]/h4")).getText(), is("\\\"Meow!Meow!\\\""));
  }
  @Test
  public void dEFECT3FUNGREETACATWITHNAME() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    driver.get("https://cs1632.appspot.com/greet-a-cat/Jennyanydots");
    assertThat(driver.findElement(By.xpath("//div[2]/h4")).getText(), is("\\\"Jennyanydots is not here.\\\""));
  }
  */
}

